# Global defaults.
global:
  # Minimum interval between re-issuing a query on a target: by default (0s) the query is executed on every scrape.
  min_interval: 0s
  # Prometheus times out scrapes after 10s by default, give ourselves a bit of headroom.
  scrape_timeout: 9s

# Jobs are equivalent to jobs in the Prometheus configuration: they group similar targets with similar metrics together. 
jobs:
  # All metrics from all targets get a `job` label, set to this value.
  - job_name: mssql

    # The set of collectors (defined below) to be applied to all targets in this job.
    collectors: [mssql_standard]

    # Similar to the Prometheus configuration, multiple sets of targets may be defined, each with an optional set of
    # labels to be applied to all metrics.
    static_configs:
      - targets:
          'dbserver1.example.com:1433': 'sqlserver://prom_user:prom_password@dbserver1.example.com:1433'
          'dbserver2.example.com:1433': 'sqlserver://prom_user:prom_password@dbserver2.example.com:1433'
        labels:
          env: 'prod'

      - targets:
          'testdb.example.com:1433': 'sqlserver://prom_user:prom_password@testdb.example.com:1433'
        labels:
          env: 'test'

# Collectors may be defined inline (under `collectors`) or loaded from `collector_files` (one collector per file).
collectors:

# Collector files specifies a list of globs. One collector definition is read from each matching file.
collector_files: 
  - "*.collector.yml"
